# Generated by Django 5.0.3 on 2024-03-10 16:56

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('na_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ph_number', users.models.PhoneNumberField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=5)),
                ('welt', models.FloatField()),
                ('status_c', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('personal_code', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('skill', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('picture_pro', models.BinaryField()),
                ('samat', models.CharField(max_length=50)),
                ('end_madrak', models.CharField(max_length=50)),
                ('shba', models.CharField(max_length=30)),
                ('date_start', models.DateField()),
                ('date_accept', models.DateField()),
                ('number_accept', models.IntegerField()),
                ('na_code_accept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ph_number', users.models.PhoneNumberField(max_length=20, primary_key=True, serialize=False)),
                ('f_x', models.FloatField()),
                ('f_y', models.FloatField()),
                ('e_x', models.FloatField()),
                ('e_y', models.FloatField()),
                ('name_sdd', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('ph_number', users.models.PhoneNumberField(max_length=20, primary_key=True, serialize=False)),
                ('identifi_code', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('sc_cart_na', models.BinaryField()),
                ('sc_cart_g', models.BinaryField()),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=5)),
                ('picture_pro', models.BinaryField()),
                ('na_code', models.CharField(max_length=10, unique=True)),
                ('shba', models.CharField(max_length=30)),
                ('welt', models.FloatField()),
                ('status_d', models.CharField(max_length=15)),
                ('mileage_per_month', models.FloatField()),
                ('id_employ', models.IntegerField()),
                ('date_certificate', models.DateField()),
                ('date_acc_final', models.DateField()),
                ('date_acc_bad_luck', models.DateField()),
                ('identifi_code_super', models.IntegerField()),
                ('l_x', models.FloatField()),
                ('l_y', models.FloatField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_de', models.CharField(max_length=25)),
                ('id_manag', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_start_manag', models.DateField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('na_code', models.CharField(max_length=10)),
                ('date_interview', models.DateField()),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'unique_together': {('date_interview', 'id_number', 'na_code')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='date_accept_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_accept_interview', to='users.interview'),
        ),
        migrations.AddField(
            model_name='employee',
            name='na_code_accept_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='na_code_accept_interview', to='users.interview'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_accept_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_accept_interview', to='users.interview'),
        ),
        migrations.CreateModel(
            name='Nutablty',
            fields=[
                ('nutablty_driver', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ph_number', users.models.PhoneNumberField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_pass', models.CharField(max_length=15)),
                ('phone_number', users.models.PhoneNumberField(max_length=20)),
                ('exp_date', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('message_id', models.CharField(db_index=True, max_length=10, null=True)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id_department', models.IntegerField(primary_key=True, serialize=False)),
                ('id_employee', models.IntegerField(unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
    ]
